### ISSUE TITLE
复制CLOVER文件到EFI文件内后没有这一个启动项呢

### ISSUE THREAD

**Issue by Moonjer** [liyafe1997/hackintosh-hp-omen-15-2017-EFI#1]
复制CLOVER文件到EFI文件内后没有这一个启动项呢
![image](https://github.com/user-attachments/assets/382fd041-e5e9-4178-84a5-e282da4b1433)

**Comment by liyafe1997** [comment]
都需要手动添加的

**Comment by Moonjer** [comment]
我还以为下载可以直接用，哈哈，刚开始研究，不太懂
