### ISSUE TITLE
HDMI 外接显示器

### ISSUE THREAD

**Issue by Adek2012** [liyafe1997/hackintosh-hp-omen-15-2017-EFI#2]
兄弟你屏蔽独显之后，HDMI 接口能使用吗？

**Comment by liyafe1997** [comment]
当然不行啦，不屏蔽也用不了，因为HDMI直连NVIDIA独显的，没驱动。
如果有外接显示器的需求可以用USB DisplayLink的方案

**Comment by Adek2012** [comment]
> 当然不行啦，不屏蔽也用不了，因为HDMI直连NVIDIA独显的，没驱动。 如果有外接显示器的需求可以用USB DisplayLink的方案

在之前的 10.13.6 中可不可以使用 NVIDIA 的 webdriver 驱动？usb 外接画质损失太厉害了

**Comment by liyafe1997** [comment]
> > 当然不行啦，不屏蔽也用不了，因为HDMI直连NVIDIA独显的，没驱动。 如果有外接显示器的需求可以用USB DisplayLink的方案
> 
> 在之前的 10.13.6 中可不可以使用 NVIDIA 的 webdriver 驱动？usb 外接画质损失太厉害了

那个我没试过
DisplayLink画质和帧率都没问题，我用Dell D6000扩展坞日常带2块2k60Hz的显示器非常完美，同时这也是M系非Pro芯片Mac外接2块以上屏幕的最佳解决方案。
